project:
  type: website
  output-dir: docs
  
website:
  search: false
  title: "Andrea Gradassi"
  navbar:
    left:
      - projects.qmd
      - experiments.qmd
      - cv.qmd
    right:
      - icon: github
        href: https://github.com/AndGrad
      - icon: twitter
        href: https://twitter.com/andrea_gradassi
      - text: "{{< iconify academicons google-scholar size=lg >}}"
        href: https://scholar.google.com/citations?user=xa8FLKMAAAAJ&hl=en
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual
bibliography: mypapers.bib
suppress-bibliography: true 
link-bibliography: true
csl: apa-cv.csl
nocite: '@*'

