---
title: "Research"
toc: false
---

::: {#res_intro style="background-color:rgba(218,218,218,.4);padding:25px; border-radius:10px; box-shadow:20px;"}
I am currently a Postdoctoral Researcher at [LABSS](https://labss.istc.cnr.it/){target="_blank"} (Laboratory for Agent-Based Social Simulation, ISTC-CNR, Rome), where I work on the Norms\@Risk project. There, I study how individual differences in social norm learning, can facilitate or inhibit the spread of cooperation in social networks.

In my PhD I studied [social learning strategies](https://www.sciencedirect.com/science/article/pii/S1364661318300949){target="_blank"} in adolescents and adults. I looked at what type of peers (close friends, popular, smart) are most influential within classrooms, what types of social cues (confidence, expertise, majority) people use when they look at others' opinions, and whether following others is beneficial or not. The main outcomes of my PhD projects are:

1.  Students in classrooms learn more from those socially close to them in their social network, those who are considered smart, or popular (Gradassi et al., 2023).

2.  Confident people are followed more, even when there is no information on whether they are right or not (Gradassi et al., 2026).

3.  High-status teenagers can boost prosocial behaviour of their classmates (Gradassi et al., 2024, *preprint*).

4.  Adolescents learn to use social cues of confidence and expertise to improve their decisions over development (in prep.).

5.  Adolescents use social information more flexibly than adults during exploration (Gradassi et al., 2025, *preprint*).

Link to full thesis: [PhD Dissertation](https://pure.uva.nl/ws/files/291080639/Thesis.pdf)
:::

### Selected publications and pre-prints

**Gradassi, A**., van den Bos, W., & Molleman, L. (2026). Own and others' confidence in social information use. *iScience*. [https://doi.org/10.1016/j.isci.2026.115968](https://doi.org/10.1016/j.isci.2026.115968){.uri target="_blank"}

**Gradassi, A**., van den Bos, W., & Ciranka, S. (2025). Adolescents use social information more flexibly than adults during exploration. *OSF Preprint*. [https://osf.io/43ypn_v1](https://osf.io/43ypn_v1){.uri target="_blank"}

**Gradassi, A**., Slagter, S. K., Pinho, A. da S., Molleman, L., & van den Bos, W. (2023). Network distance and centrality shape social learning in the classroom. *School Psychology*, 38(2), 67--78. [https://doi.org/10.1037/spq0000490](https://doi.org/10.1037/spq0000490){.uri target="_blank"}

Slagter, S. K., **Gradassi, A**., van Duijvenvoorde, A. C. K., & van den Bos, W. (2023). Identifying who adolescents prefer as source of information within their social network. *Scientific Reports*, 13(1), 20277. [https://doi.org/10.1038/s41598-023-46994-0](https://doi.org/10.1038/s41598-023-46994-0){.uri target="_blank"}

Molleman, L., Tump, A. N., **Gradassi, A**., Herzog, S., Jayles, B., Kurvers, R. H. J. M., & van den Bos, W. (2020). Strategies for integrating disparate social information. *Proceedings of the Royal Society B*, 287(1939), 20202413. [https://doi.org/10.1098/rspb.2020.2413](https://doi.org/10.1098/rspb.2020.2413){.uri target="_blank"}

<a href="https://scholar.google.com/citations?user=xa8FLKMAAAAJ&hl=en" target="_blank"> <button type="button" class="btn btn-primary">Full Publications</button> </a>

### Broad interests and future work

What I find most rewarding is to draw bridges between disciplines and try to look at problems at multiple levels of abstraction. I see myself as an interdisciplinary social behavioral researcher, and these are the broad research fields and themes that inspire me and that I would like to work on in the future.

**Social Psychology:** How humans perceive social relationships and how they learn from their peers.

**Evolutionary biology/anthropology:** What makes groups come together (cooperation) and break apart (conflict).

**Behavioral economics/policy-making:** How we can encourage cooperation with behavioral interventions.

**Sociology:** How social networks structures and socioeconomic factors shape opportunities and life outcomes.

**Education:** How to design learning environments that take into account developmental differences in how and from who humans learn.
