---
title: "Research"
toc: false
---

::: {#res_intro style="background-color:rgba(218,218,218,.4);padding:25px; border-radius:10px; box-shadow:20px;"}
In my PhD I study [social learning strategies](https://www.sciencedirect.com/science/article/pii/S1364661318300949){target="_blank"} in adolescents and adults. I look at what type of peers (close friends, popular, smart) are most influential within classrooms, what types of social cues (confidence, expertise, majority) people use when they look at others' opinions, and weather following others is beneficial or not. The main outcomes of my projects are:

1.  Students in classrooms learn more from those socially close to them in their social network, those who are considered smart, or popular (Gradassi et al., 2023).

2.  Confident people are followed more, even when there is no information on whether they are right or not (Gradassi et al., 2022).

3.  High-status teenagers can boost prosocial behaviour of their classmates (in prep.).

4.  Adolescents learn to use social cues of confidence and expertise to improve their decisions over development (in prep.).

5.  Sensitivity to peer influence in adolescents is helpful to explore uncertain environments (in progress).
:::

### Selected publications

**Gradassi, A**., Slagter, S. K., Pinho, A. da S., Molleman, L., & van den Bos, W. (2023). Network distance and centrality shape social learning in the classroom. School Psychology (Washington, D.C.), 38(2), 67--78. [https://doi.org/10.1037/spq0000490](https://doi.org/10.1037/spq0000490){.uri target="_blank"}   <a href="gradassietal2022.pdf" download="gradassi2023.pdf"> <button type="button" class="btn btn-info btn-sm">PDF</button></a> <a href="https://github.com/AndGrad/soc_learning_network" target="_blank"> <button type="button" class="btn btn-success btn-sm">code</button></a>

Slagter, S. K., **Gradassi, A**., van Duijvenvoorde, A. C. K., & van den Bos, W. (2023). Identifying who adolescents prefer as source of information within their social network. Scientific Reports, 13(1), 20277. [https://doi.org/10.1038/s41598-023-46994-0](https://doi.org/10.1038/s41598-023-46994-0){.uri target="_blank"}   <a href="gradassietal2022.pdf" download="gradassi2023.pdf"> <button type="button" class="btn btn-info btn-sm">PDF</button></a> <a href="https://osf.io/b5c9d/" target="_blank"> <button type="button" class="btn btn-success btn-sm">code</button></a>

**Gradassi, A**., van den Bos, W., & Molleman, L. (2022). Confidence of others trumps confidence of self in social information use. PsyArXiv. [https://psyarxiv.com/mqyu2/](https://psyarxiv.com/mqyu2/){.uri target="_blank"}   <a href="gradassietal2022.pdf" download="gradassi2023.pdf"> <button type="button" class="btn btn-info btn-sm">PDF</button></a> <a href="https://github.com/AndGrad/Confidence-Self-Others" target="_blank"> <button type="button" class="btn btn-success btn-sm">code</button></a>

<a href="https://scholar.google.com/citations?user=xa8FLKMAAAAJ&hl=en" target="_blank"> <button type="button" class="btn btn-primary">Full Publications</button> </a>

### Broad interests and future work

What I find most rewarding is to draw bridges between disciplines and and try to look at problems at multiple levels of abstractions. I see myself as an interdisciplinary social behavioral researcher, and these are the broad research fields and themes that inspire me and that I would like to work on in the future.

**Social Psychology:** How humans perceive social relationships and how they learn from their peers.

**Evolutionary biology/anthropology:** What makes groups come together (cooperation) and break apart (conflict).

**Behavioral economics/policy-making:** How we can encourage cooperation with behavioral interventions.

**Sociology:** How social networks structures and socioeconomic factors shape opportunities and life outcomes.

**Education:** How to design learning environments that take into account developmental differences in how and from who humans learn.
